package com.techelevator;

public class VendingMachineTests {
	
	//ALL UTILIZED CLASSES HAVE TESTS--WRITING UNIT TESTS FOR VENDING MACHINE
	//IS NOT EFFICIENT BECAUSE IT REQUIRES CONSTRUCTION OF A NEW PRINTER
	//TO COMPLETE EACH OF THE METHODS
	
	//MANUAL TESTING OF VENDING MACHINE RECOMMENDED
	//MANUAL TESTING OF ALL METHODS PASSED 2/6/2021

}
